name = "CSSUtil"
uuid = "70588ee8-6100-5070-97c1-3cb50ed05fe8"
version = "0.1.1"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
WebIO = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"

[compat]
Colors = "0.10, 0.12"
JSON = "0.20, 0.21"
Measures = "0.2, 0.3"
WebIO = "0.7, 0.8"


